language: python
python:
    - "2.7"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database cleansweep_test;' -U postgres

install: pip install -r requirements.txt
script: python -m cleansweep.tests.test_models
env:
  - DATABASE_URL="postgresql://postgres@/cleansweep_test" SQLALCHEMY_ECHO=TRUE

notifications:
  slack: cleansweep:XCwDDECYJgCmWyyrH7fSyNfI
