version: "2"
services:
  web:
    build: .
    environment:
      - CLEANSWEEP_SETTINGS=/etc/cleansweep.cfg
    ports:
     - "5000:${CLEANSWEEP_PORT}"
    volumes:
     - .:/code
     - ./config/cleansweep_docker.cfg:/etc/cleansweep.cfg
    links:
     - redis
     - db
  redis:
    image: redis
  db:
    image: postgres
    volumes:
    - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: {}
