"""Initial Schema

Revision ID: 47d71663e96d
Revises: None
Create Date: 2015-09-17 22:12:44.061964

"""

# revision identifiers, used by Alembic.
revision = '47d71663e96d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unsubscribe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('place_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('short_name', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('iparent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['iparent_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['place_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'name', 'date')
    )
    op.create_table('committee_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('place_type_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['place_type_id'], ['place_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'place_type_id', 'slug')
    )
    op.create_table('pending_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('voterid', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='pending_member_status'), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('voterid', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSON(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('place_parents',
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['place.id'], )
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('voterid', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_email'), 'contact', ['email'], unique=False)
    op.create_index(op.f('ix_contact_phone'), 'contact', ['phone'], unique=False)
    op.create_index(op.f('ix_contact_place_id'), 'contact', ['place_id'], unique=False)
    op.create_index(op.f('ix_contact_voterid'), 'contact', ['voterid'], unique=False)
    op.create_table('committee_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_type_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('multiple', sa.Boolean(), nullable=True),
    sa.Column('permission', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['committee_type_id'], ['committee_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['committee_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('data', postgresql.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_person_id'), 'audit', ['person_id'], unique=False)
    op.create_index(op.f('ix_audit_place_id'), 'audit', ['place_id'], unique=False)
    op.create_index(op.f('ix_audit_user_id'), 'audit', ['user_id'], unique=False)
    op.create_table('mv_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='mv_request_status'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['place.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'member_id')
    )
    op.create_index(op.f('ix_mv_request_member_id'), 'mv_request', ['member_id'], unique=False)
    op.create_index(op.f('ix_mv_request_place_id'), 'mv_request', ['place_id'], unique=False)
    op.create_table('committee_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('committee_id', sa.Integer(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], ['committee.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['committee_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('committee_member')
    op.drop_index(op.f('ix_mv_request_place_id'), table_name='mv_request')
    op.drop_index(op.f('ix_mv_request_member_id'), table_name='mv_request')
    op.drop_table('mv_request')
    op.drop_index(op.f('ix_audit_user_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_place_id'), table_name='audit')
    op.drop_index(op.f('ix_audit_person_id'), table_name='audit')
    op.drop_table('audit')
    op.drop_table('committee')
    op.drop_table('committee_role')
    op.drop_index(op.f('ix_contact_voterid'), table_name='contact')
    op.drop_index(op.f('ix_contact_place_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_phone'), table_name='contact')
    op.drop_index(op.f('ix_contact_email'), table_name='contact')
    op.drop_table('contact')
    op.drop_table('place_parents')
    op.drop_table('member')
    op.drop_table('pending_member')
    op.drop_table('committee_type')
    op.drop_table('stats')
    op.drop_table('place')
    op.drop_table('place_type')
    op.drop_table('unsubscribe')
    ### end Alembic commands ###
