"""empty message

Revision ID: ca21d44bd9f
Revises: cb4ac67bb2b
Create Date: 2016-01-15 03:36:52.793827

"""

# revision identifiers, used by Alembic.
revision = 'ca21d44bd9f'
down_revision = 'cb4ac67bb2b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('door2door_entry', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('door2door_entry', sa.Column('phone', sa.Text(), nullable=False))
    op.add_column('door2door_entry', sa.Column('place_id', sa.Integer(), nullable=False))
    op.add_column('door2door_entry', sa.Column('voters_in_family', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'door2door_entry', ['phone'])
    op.create_foreign_key(None, 'door2door_entry', 'place', ['place_id'], ['id'])
    op.drop_constraint(u'member_email_key', 'member', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'member_email_key', 'member', ['email'])
    op.drop_constraint(None, 'door2door_entry', type_='foreignkey')
    op.drop_constraint(None, 'door2door_entry', type_='unique')
    op.drop_column('door2door_entry', 'voters_in_family')
    op.drop_column('door2door_entry', 'place_id')
    op.drop_column('door2door_entry', 'phone')
    op.drop_column('door2door_entry', 'name')
    ### end Alembic commands ###
