"""Modified the unique constraint on committee_type table.

See Issue#117

Revision ID: cb4ac67bb2b
Revises: 47d71663e96d
Create Date: 2015-10-01 23:40:24.130955

"""

# revision identifiers, used by Alembic.
revision = 'cb4ac67bb2b'
down_revision = '47d71663e96d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'committee_type_place_id_place_type_id_slug_key', 'committee_type', type_='unique')
    op.create_unique_constraint(None, 'committee_type', ['place_id', 'slug'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'committee_type', type_='unique')
    op.create_unique_constraint(u'committee_type_place_id_place_type_id_slug_key', 'committee_type', ['place_id', 'place_type_id', 'slug'])
    ### end Alembic commands ###
