"""Adding old tables 2

Revision ID: 2f4fc3a48e42
Revises: 
Create Date: 2015-08-17 13:44:31.939080

"""

# revision identifiers, used by Alembic.
revision = '2f4fc3a48e42'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mv_request')
    op.drop_table('committee_role')
    op.drop_table('audit')
    op.drop_table('committee')
    op.drop_table('committee_type')
    op.drop_table('committee_member')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('committee_member',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('committee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['committee_id'], [u'committee.id'], name=u'committee_member_committee_id_fkey'),
    sa.ForeignKeyConstraint(['member_id'], [u'member.id'], name=u'committee_member_member_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], [u'committee_role.id'], name=u'committee_member_role_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'committee_member_pkey')
    )
    op.create_table('committee_type',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('committee_type_id_seq'::regclass)"), nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], [u'place.id'], name=u'committee_type_place_id_fkey'),
    sa.ForeignKeyConstraint(['place_type_id'], [u'place_type.id'], name=u'committee_type_place_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'committee_type_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('committee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], [u'place.id'], name=u'committee_place_id_fkey'),
    sa.ForeignKeyConstraint(['type_id'], [u'committee_type.id'], name=u'committee_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'committee_pkey')
    )
    op.create_table('audit',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSON(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], [u'member.id'], name=u'audit_person_id_fkey'),
    sa.ForeignKeyConstraint(['place_id'], [u'place.id'], name=u'audit_place_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'member.id'], name=u'audit_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'audit_pkey')
    )
    op.create_table('committee_role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('committee_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('multiple', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('permission', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['committee_type_id'], [u'committee_type.id'], name=u'committee_role_committee_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'committee_role_pkey')
    )
    op.create_table('mv_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('place_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM(u'pending', u'approved', u'rejected', name='mv_request_status'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['member_id'], [u'member.id'], name=u'mv_request_member_id_fkey'),
    sa.ForeignKeyConstraint(['place_id'], [u'place.id'], name=u'mv_request_place_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'mv_request_pkey')
    )
    ### end Alembic commands ###
